### PR TITLE
Bump gatsby peer dependency to v3

### LINKED ISSUE #2: Support gatsby v3
hi there,

Just so it is noted, you might already be working on it, but the current version of this plugin is marked as incompatible with gatsby v3.
So supporting v3 would be great :).

### PR DESCRIPTION
**Pull request by sylvainDNS**
closes #2

### CODE REVIEW

**Comment by klintan** [comment]
Any news on this ? :)

**Comment by sylvainDNS** [comment]
Just waiting @jzabala for the review :blush: 

But guys please put a star on his repo, there is more react on my comment than on this repo! Give him support!

**Comment by jzabala** [comment]
Thank you very much for the PR and support @sylvainDNS. I really appreciate it :D

**Comment by rwitchell** [comment]
this should be `^1` or `^2.0 || ^3.0 || ^4.0` as the package has no reason not to work with gatsby v2 or v3

**Pull request merged**
